CORE/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("accounts.urls")),
        path("contacts/", include("contacts.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + debug_toolbar_urls()
)

accounts/urls.py
from django.urls import path
from rest_framework.routers import SimpleRouter
from . import views

app_name = "accounts"


urlpatterns = [
    path("", views.Login.as_view(), name="login"),
    path("register/", views.Register.as_view(), name="register"),
    path("logout/", views.logout_view, name="logout"),
    path("api/register/", views.RegisterUserAPI.as_view(), name="register_api"),
]

contacts/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


from contacts import views

app_name = "contacts"

contacts_api_router = SimpleRouter()
contacts_api_router.register("api", views.ContactsViewsetAPI, basename="recipes-api")

site = [
    path("", views.IndexBaseView.as_view(), name="index"),
    path("details/<int:pk>", views.ContactDetailsView.as_view(), name="details"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateContact.as_view(), name="create"),
    path("edit/<int:pk>", views.EditContact.as_view(), name="edit"),
    path("delete/<int:pk>", views.DeleteContact.as_view(), name="delete"),
]

api = [
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("", include(contacts_api_router.urls)),
]

urlpatterns = site + api

templates/partials/_footer.html
<footer class="footer">
  <div class="footer-presentation">
    <p class="footer-heading">Author presentation</p>
    <p class="author-description">
      Hey! My name is Vinícius Eugênio, I am a 17 years old developer,
      passionate about web-development and a compassionate human being. If
      you would like to contact me, feel free.
    </p>
  </div>

  <div class="footer-socials">
    <p class="footer-heading">Social links</p>

    <ul class="social-links">
      <li>
        <a href="https://linkedin.com/in/eugencius" class="social-link" target="_blank">
          <ion-icon name="logo-linkedin"></ion-icon>
        </a>
      </li>

      <li>
        <a href="mailto:viniciuseugeniovhe@gmail.com" class="social-link" target="_blank">
          <ion-icon name="mail-outline"></ion-icon>
        </a>
      </li>
    </ul>

  </div>
</footer>

templates/partials/_head.html
{% load static %}

<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>Eugenda &mdash; The agenda you need</title>

<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link
  href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300..900;1,300..900&display=swap"
  rel="stylesheet"
/>

<link rel="stylesheet" href="{% static "css/styles.css" %}"> 
<link rel="stylesheet" href="{% static "css/general.css" %}">
<script defer src="{% static "js/scripts.js" %}"></script>

<script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
<script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>

templates/partials/_messages.html
{% if messages %}
  <div class="messages-container">
    {% if messages %}
      {% for message in messages %}
        <div class="message {{ message.tags }}">
          <ion-icon name="notifications-outline"></ion-icon>
          <span>{{ message }}</span>
          
          <button class="btn notification-close">
            <ion-icon class="icon-close" name="close-circle-outline"></ion-icon>
          </button>
        </div>  
      {% endfor %}
    {% endif %}
  </div>
{% endif %}

templates/partials/_nav.html
{% load static %}

<header class="header">
  <a class="header-logo" href="{% url "contacts:index" %}">
    {% comment %} <div class="eugenda-svg" role='img'></div> {% endcomment %}
    <img src="{% get_media_prefix %}/icons/eugenda.svg" width="150" height="auto" alt="">
  </a>

  <nav class="main-nav">
    <ul class="main-nav-list">
      <li>
        <form class="search-form" action="{% url "contacts:search" %}" method="GET">
          <input type="text" class="input-search" name="q" id="input-search" placeholder="Search for a contact">
          <button class="btn-search" type="submit">
            <ion-icon class="search-icon" name="search-outline"></ion-icon>
          </button>
        </form>
      </li>
      <li><a href="{% url "contacts:create" %}" class="main-nav-link">Create</a></li>
      <li><a href="#" class="main-nav-link">Profile</a></li>
      <li><a href="#" class="main-nav-link">
        <form class="form-logout" action="{% url "accounts:logout" %}" method="post">
          {% csrf_token %}
          <button class="btn-default" type="submit">
            Exit
          </button>
        </form>
      </a></li>
    </ul>
  </nav>
</header>

templates/partials/_pagination.html
{% if is_paginated %}
  <nav class="pagination-container">
    <ul class="pagination">
      {% if contacts.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ contacts.previous_page_number }}{{ search_query }}">
            <ion-icon class="page-icon" name="chevron-back-outline"></ion-icon>      
          </a>
        </li>
      {% endif %}

      {% for page in page_range %}
        {% if page == current_page %}
          <li class="page-item page-active">
            <a class="page-link" href="?page={{ page }}{{ search_query }}">{{ page }}</a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page }}{{ search_query }}">{{ page }}</a>
          </li>
        {% endif %}
    
      {% endfor %}

      {% if contacts.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ contacts.next_page_number }}{{ search_query }}">
              <ion-icon class="page-icon" name="chevron-forward-outline"></ion-icon>
            </a>
          </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}