CORE/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("accounts.urls")),
        path("contacts/", include("contacts.urls")),
    ]
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    + debug_toolbar_urls()
)

contacts/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
    TokenVerifyView,
)


from contacts import views

app_name = "contacts"

contacts_api_router = SimpleRouter()
contacts_api_router.register("api", views.ContactsViewsetAPI, basename="recipes-api")

site = [
    path("", views.IndexBaseView.as_view(), name="index"),
    path("details/<int:pk>", views.ContactDetailsView.as_view(), name="details"),
    path("search/", views.SearchView.as_view(), name="search"),
    path("create/", views.CreateContact.as_view(), name="create"),
    path("edit/<int:pk>", views.EditContact.as_view(), name="edit"),
    path("delete/<int:pk>", views.DeleteContact.as_view(), name="delete"),
]

api = [
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/token/verify/", TokenVerifyView.as_view(), name="token_verify"),
    path("", include(contacts_api_router.urls)),
]

urlpatterns = site + api

contacts/models.py
import os

from django.db import models
from django.urls import reverse
from django.conf import settings
from django.utils import timezone
from django.core.files import File
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=32)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Contact(models.Model):
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64, null=True, blank=True)
    phone = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    creation_date = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True, null=True)
    category = models.ForeignKey(
        Category, blank=True, null=True, on_delete=models.SET_NULL
    )
    image = models.ImageField(blank=True, upload_to="images/")

    def get_full_name(self):
        return self.name if not self.surname else f"{self.name} {self.surname}"

    def __str__(self):
        return f"{self.name} {self.surname}"

    def get_absolute_url(self):
        return reverse("contacts:details", kwargs={"pk": self.pk})

    def save(self, *args, **kwargs):
        if not self.image:
            default_image_path = os.path.join("images", "default.png")

            with open(os.path.join(settings.MEDIA_ROOT, default_image_path), "rb") as f:
                self.image.save("default.png", File(f), save=False)

        super().save(*args, **kwargs)

contacts/forms.py
import re

from django import forms
from django.forms import ValidationError

from .models import Contact
from templates.static import utils


class CreateContactForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["description"].widget.attrs.update(
            {"container_class": "description-input"}
        )

        self.fields["category"]

        # self.fields["image"].widget.attrs.update({"container_class": "image-input"})

        for field_name in self.fields:
            self.fields[field_name].widget.attrs.update({"class": "field-input"})

    phone = forms.CharField(
        min_length=11,
        max_length=11,
    )

    class Meta:
        model = Contact
        fields = [
            "name",
            "surname",
            "phone",
            "email",
            "description",
            "image",
            "category",
        ]

    def clean(self):
        fields = self.cleaned_data

        name = fields.get("name")
        surname = fields.get("surname")

        if name and surname and name == surname:
            error = "The name and surname cannot be equal."
            raise ValidationError(
                {
                    "name": error,
                    "surname": error,
                }
            )

    def clean_phone(self):
        phone = self.cleaned_data.get("phone")

        if re.search(r"[^0-9]", phone):
            raise ValidationError("The phone field must contain only numbers")

        return phone

contacts/views.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from . import forms
from .models import Contact
from templates.static import utils


User = get_user_model()
LOGIN_URL = "accounts:login"
PER_PAGE = 9


# Create your views here.


class IndexBaseView(LoginRequiredMixin, ListView):
    model = Contact
    ordering = ["-id"]
    context_object_name = "contacts"
    template_name = "contacts/index.html"
    login_url = LOGIN_URL
    redirect_field_name = "next"

    def get_queryset(self):
        qs = super().get_queryset()
        user = User.objects.get(username=self.request.user.username)

        qs = qs.filter(creator=user)
        qs = qs.select_related("category")
        qs = qs.defer("creator", "creation_date", "description")

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page_obj, page_range, current_page = utils.make_pagination(
            request=self.request,
            queryset=context.get("contacts"),
            per_page=PER_PAGE,
        )

        context.update(
            {
                "contacts": page_obj,
                "page_range": page_range,
                "current_page": current_page,
                "is_paginated": len(page_range) > 1,
            }
        )

        return context


class SearchView(IndexBaseView):
    def get_queryset(self):
        qs = super().get_queryset()

        search_term = self.request.GET.get("q", "").strip()
        qs = qs.filter(
            Q(name__icontains=search_term) | Q(surname__icontains=search_term)
        )

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_term = self.request.GET.get("q", "").strip()

        context.update(
            {
                "search_query": f"&q={search_term}",
            }
        )

        return context


class CreateContact(LoginRequiredMixin, CreateView):
    model = Contact
    form_class = forms.CreateContactForm
    template_name = "contacts/create_contact.html"
    login_url = LOGIN_URL
    redirect_field_name = "next"

    def form_valid(self, form):
        creator = User.objects.get(username=self.request.user.username)
        contact = form.save(commit=False)
        contact.creator = creator
        contact.image = self.request.FILES.get("image")

        contact.save()

        messages.add_message(
            self.request, messages.SUCCESS, "A new contact was created!"
        )

        return redirect("contacts:index")


class ContactDetailsView(LoginRequiredMixin, DetailView):
    model = Contact
    template_name = "contacts/contact_details.html"
    login_url = LOGIN_URL
    pk_url_kwarg = "pk"
    context_object_name = "contact"


class EditContact(LoginRequiredMixin, UpdateView):
    model = Contact
    form_class = forms.CreateContactForm
    login_url = LOGIN_URL
    pk_url_kwarg = "pk"
    template_name = "contacts/edit_contact.html"

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.SUCCESS, "Contact was successfully updated."
        )

        return super().form_valid(form)


class DeleteContact(LoginRequiredMixin, DeleteView):
    model = Contact
    login_url = LOGIN_URL
    success_url = reverse_lazy("contacts:index")

    def get(self, *args, **kwargs):
        messages.add_message(self.request, messages.ERROR, "Ops! You can't do this.")
        return redirect("contacts:index")

    def post(self, request, *args, **kwargs):
        messages.add_message(
            self.request, messages.SUCCESS, "The contact was successfully deleted."
        )
        return super().post(request, *args, **kwargs)

contacts/views/api.py
from rest_framework.response import Response
from rest_framework import status
from rest_framework.pagination import PageNumberPagination
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticated

from ..models import Contact
from ..permissions import IsOwner
from ..serializers import ContactSerializer


class FilterQuerysetUser:
    def get_queryset(self):
        qs = super().get_queryset()

        user = self.request.user
        qs = qs.filter(creator=user)

        return qs


class ContactsViewsetAPI(FilterQuerysetUser, ModelViewSet):
    queryset = Contact.objects.all()
    serializer_class = ContactSerializer
    pagination_class = PageNumberPagination
    permission_classes = [IsAuthenticated, IsOwner]

    def get_queryset(self):
        qs = super().get_queryset().order_by("-id")
        return qs

    def create(self, request, *args, **kwargs):
        user = request.user

        contact = ContactSerializer(
            data=request.data,
            partial=True,
        )
        contact.is_valid(raise_exception=True)
        contact.save(creator=user)

        return Response(contact.data, status=status.HTTP_201_CREATED)

contacts/views/site.py
from django.urls import reverse_lazy
from django.shortcuts import redirect
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.views.generic import ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .. import forms
from ..models import Contact
from templates.static import utils

from CORE.settings import env

User = get_user_model()
LOGIN_URL = "accounts:login"
PER_PAGE = env("PER_PAGE")


# Create your views here.


class IndexBaseView(LoginRequiredMixin, ListView):
    model = Contact
    ordering = ["-id"]
    context_object_name = "contacts"
    template_name = "contacts/index.html"
    login_url = LOGIN_URL
    redirect_field_name = "next"

    def get_queryset(self):
        qs = super().get_queryset()
        user = User.objects.get(username=self.request.user.username)

        qs = qs.filter(creator=user)
        qs = qs.select_related("category")
        qs = qs.defer("creator", "creation_date", "description")

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        page_obj, page_range, current_page = utils.make_pagination(
            request=self.request,
            queryset=context.get("contacts"),
            per_page=PER_PAGE,
        )

        context.update(
            {
                "contacts": page_obj,
                "page_range": page_range,
                "current_page": current_page,
                "is_paginated": len(page_range) > 1,
            }
        )

        return context


class SearchView(IndexBaseView):
    def get_queryset(self):
        qs = super().get_queryset()

        search_term = self.request.GET.get("q", "").strip()
        qs = qs.filter(
            Q(name__icontains=search_term) | Q(surname__icontains=search_term)
        )

        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_term = self.request.GET.get("q", "").strip()

        context.update(
            {
                "search_query": f"&q={search_term}",
            }
        )

        return context


class CreateContact(LoginRequiredMixin, CreateView):
    model = Contact
    form_class = forms.CreateContactForm
    template_name = "contacts/create_contact.html"
    login_url = LOGIN_URL
    redirect_field_name = "next"

    def form_valid(self, form):
        creator = User.objects.get(username=self.request.user.username)
        contact = form.save(commit=False)
        contact.creator = creator
        contact.image = self.request.FILES.get("image")

        contact.save()

        messages.add_message(
            self.request, messages.SUCCESS, "A new contact was created!"
        )

        return redirect("contacts:index")


class ContactDetailsView(LoginRequiredMixin, DetailView):
    model = Contact
    template_name = "contacts/contact_details.html"
    login_url = LOGIN_URL
    pk_url_kwarg = "pk"
    context_object_name = "contact"

    def get(self, *args, **kwargs):
        user = self.request.user

        if self.get_object().creator != user:
            messages.add_message(
                self.request, messages.ERROR, "Ops! You can't do this."
            )
            return redirect("contacts:index")

        return super().get(*args, **kwargs)


class EditContact(LoginRequiredMixin, UpdateView):
    model = Contact
    form_class = forms.CreateContactForm
    login_url = LOGIN_URL
    pk_url_kwarg = "pk"
    template_name = "contacts/edit_contact.html"

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.SUCCESS, "Contact was successfully updated."
        )

        return super().form_valid(form)


class DeleteContact(LoginRequiredMixin, DeleteView):
    model = Contact
    login_url = LOGIN_URL
    success_url = reverse_lazy("contacts:index")

    def get(self, *args, **kwargs):
        messages.add_message(self.request, messages.ERROR, "Ops! You can't do this.")
        return redirect("contacts:index")

    def post(self, request, *args, **kwargs):
        messages.add_message(
            self.request, messages.SUCCESS, "The contact was successfully deleted."
        )
        return super().post(request, *args, **kwargs)

contacts/templates/contacts/contact_details.html
{% extends "base.html" %}


{% block content %}

<div class="contact-details-page">
  <div class="details-img-box">
    <img class="details-contact-image" src="{{ contact.image.url }}" alt="A contact photo">
  </div>
  <div class="details-info-box">
    <ul class="details-list">
      <li>
        <h1 class="heading-primary">{{ contact.get_full_name }}</h1>
      </li>

      <li>
        <p class="info-title">
          <ion-icon class="details-icon" name="mail-outline"></ion-icon>
          <span>E-mail</span>
        </p>
        <p class="information" >{{ contact.email }}</p>
      </li>
      
      <li>
        <p class="info-title">
          <ion-icon class="details-icon" name="call-outline"></ion-icon>
          <span>Phone</span>
        </p>
        <p class="information">{{ contact.phone}}</p>
      </li>

      {% if contact.category %}
        <li>
          <p class="info-title">
            <ion-icon class="details-icon" name="list-outline"></ion-icon>
            <span>Category</span>
          </p>
          <p class="information" >{{ contact.category }}</p>
        </li>
      {% endif %}
        
      <li>
        <p class="info-title">
          <ion-icon class="details-icon" name="document-text-outline"></ion-icon>
          <span>Description</span>
        </p>
        <p class="contact-description" >{{contact.description}}</p>
      </li>
    </ul>

    <div class="contact-actions">
      <a class="action-link" href="{% url "contacts:edit" contact.id %}">
        <ion-icon class="edit-icon" name="create-outline"></ion-icon>
        <span>Edit Contact</span>
      </a>
      
      <form class="form-inline form-delete" action="{% url "contacts:delete" contact.id %}" method="post">
        {% csrf_token %}
        <ion-icon class="delete-icon" name="trash-outline"></ion-icon>
        <button class="btn-default" type="submit">Delete Contact</button>
      </form>
    </div>
  </div>
</div>
{% endblock content %}

contacts/templates/contacts/create_contact.html
{% extends "base.html" %}


{% block content %}

<div class="contact-creation-page">
  <h1 class="auth-heading">Lets create a new contact!</h1>

  <div class="form-box create-contact">
    <form action="{% url "contacts:create" %}" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      
      <div class="grid grid-2-cols">
        {% for field in form %}
          <div class="{{ field.field.widget.attrs.container_class }} field-container">
            <label class="field-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            
            {% for error in field.errors %}
              <p class="form-error">{{ error }}</p>
            {% endfor %}
          </div>
        {% endfor %}
      </div>

      <button type="submit" class="btn btn-primary">Create new contact</button>
    </form>
  </div>

</div>

{% endblock content %}

contacts/templates/contacts/edit_contact.html
{% extends "base.html" %}


{% block content %}

<div class="contact-creation-page">
  <h1 class="auth-heading">Editing contact</h1>

  <div class="form-box create-contact">
    <form action="{% url "contacts:edit" contact.id %}" enctype="multipart/form-data" method="post">
      {% csrf_token %}
      
      <div class="grid grid-2-cols">
        {% for field in form %}

          {% if field.label != 'Image' %}
            <div class="{{ field.field.widget.attrs.container_class }} field-container">
              <label class="field-label" for="{{ field.id_for_label }}">{{ field.label }}</label>

              {{ field }}
              
              {% for error in field.errors %}
                <p class="form-error">{{ error }}</p>
              {% endfor %}
            </div>
          {% else %}
            <div class="{{ field.field.widget.attrs.container_class }} field-container">
              <label class="field-label" for="{{ field.id_for_label }}">{{ field.label }}</label>

              {% comment %} {{ field }} {% endcomment %}
              <input type="file" name="image" accept="image/*", class="field-input" id="id-image">

              <div class="clear-image-input">
                <label for="image-clear_id">Remove current image</label>
                <input type="checkbox" name="image-clear" id="image-clear_id">
              </div>

              {% for error in field.errors %}
                <p class="form-error">{{ error }}</p>
              {% endfor %}
            </div>
          {% endif %}

        {% endfor %}
      </div>

      <button type="submit" class="btn btn-primary">Create new contact</button>
    </form>
  </div>

</div>

{% endblock content %}

contacts/templates/contacts/index.html
{% extends "base.html" %}

{% block content %}
  <div class="contacts-page">
    <div class="contacts-container">
      <div class="contacts-list">
        {% for contact in contacts %}
        <a class="contact-card-link" href="{% url "contacts:details" contact.id %}">
          <div class="contact-card">
            <div class="contact-img-container">
              <img class="contact-image" src="{{ contact.image.url }}" alt="A contact photo">
            </div>
      
            <div class="contact-info">
              <h2 class="contact-name">{{ contact.get_full_name }}</h2>
              <p>E-mail: {{ contact.email }}</p>
              <p>Phone: {{ contact.phone }}</p>
              {% if contact.category %}
                <p>Category: {{ contact.category }}</p>
              {% endif %}
            </div>
          </div>
        </a>
        {% endfor %}    
      </div>
    </div>


    {% include "partials/_pagination.html" %}

  </div>
{% endblock content %}